Stop redeclaring TrustedHTML
Running yarn upgrade gives
the error:

error TS2451: Cannot redeclare block-scoped variable 'TrustedHTML'

which is because the late-2023 types/react
clashes with definitions from older
types/trusted-types.

Update types/dompurify to trigger
yarn to give us a more recent
trusted-types.