Restrict mobx to <6.13.0
Mobx 6.13 makes tsc error out with:

Error: node_modules/mobx/dist/types/observableset.d.ts(45,31): error TS2552: Cannot find name 'ReadonlySetLike'. Did you mean 'ReadonlySet'?

which is issue 3903 in the mobx repository.
Restrict mobx to <6.13 for now to avoid
the issue.